{
    "name": "LoanRepaymentDueDataV1",
    "namespace": "com.corevance.avro.loan.v1",
    "type": "record",
    "fields": [
        {
            "name": "loanId",
            "type": ["long"]
        },
        {
            "name": "loanAccountNo",
            "type": ["string"]
        },
        {
            "default": null,
            "name": "loanExternalId",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "currency",
            "type": [
                "null",
                "com.corevance.avro.generic.v1.CurrencyDataV1"
            ]
        },
        {
            "name": "installment",
            "type": ["com.corevance.avro.loan.v1.RepaymentDueDataV1"]
        },
        {
            "default": null,
            "name": "pastDueAmount",
            "type": [
                "null",
                "com.corevance.avro.loan.v1.RepaymentPastDueDataV1"
            ]
        },
        {
            "default": null,
            "name": "customData",
            "type": [
                "null",
                {
                    "values": "bytes",
                    "type": "map"
                }
            ]
        },
        {
            "default": null,
            "name": "originators",
            "type": [
                "null",
                {
                    "type": "array",
                    "items": "com.corevance.avro.loan.v1.OriginatorDetailsV1"
                }
            ]
        }
    ]
}
