= Step 6: Create Distribution

== Description

Create source and binary tarballs.

[source,bash,subs="attributes+"]
----
./gradlew clean
./gradlew generateLicenseReport
./gradlew srcDistTar binaryDistTar
----

Check that `corevance-provider/build/generated-resources/git/git.properties` exists. If so, continue. If not, you're likely encountering https://github.com/n0mer/gradle-git-properties/issues/233[this bug], and you need to *re-run the command above* to create proper source and binary tarballs. That `git.properties` file is supposed to end up at `BOOT-INF/classes/git.properties` in `corevance-provider-{revnumber}.jar` in the binary release tarball. Its contents are displayed at the `/corevance-provider/actuator/info` endpoint. It may be possible to fix this heisenbug entirely by https://github.com/gradle/gradle/issues/34177#issuecomment-3051970053[modifying our git properties gradle plugin config] in `corevance-provider/build.gradle`, perhaps by changing where `git.properties` is written.

Look in `corevance-war/build/distributions/` for the tarballs.

Do some sanity checks. The source tarball and the code in the release branch (at the commit with the release tag) should match.

[source,bash,subs="attributes+"]
----
cd /corevance-release-preparations
tar -xvzf path/to/apache-corevance-src-{revnumber}.tar.gz
git clone git@github.com:apache/corevance.git
cd corevance/
git switch --detach tags/{revnumber}
cd ..
diff -r corevance apache-corevance-src-{revnumber}
----

The diff won't be perfectly clean... some things are excluded from the source tarball on purpose. If you see something like this, it's OK to proceed:

[source,text]
----
Only in corevance: .atr-rat-excludes-bin.txt
Only in corevance: .atr-rat-excludes-src.txt
Only in corevance: .dockerignore
Only in corevance/corevance-branch/src/test/java: .gitkeep
Only in corevance/corevance-branch/src/test/resources: .gitkeep
Only in corevance/corevance-client/src/main/resources: .gitkeep
Only in corevance/corevance-core/src/main/java/com/corevance/infrastructure/businessdate/validation: .gitkeep
Only in corevance/corevance-core/src/test/java: .gitkeep
Only in corevance/corevance-core/src/test/resources: .gitkeep
Only in corevance/corevance-doc/src/resources/fonts: .gitkeep
Only in corevance/corevance-doc/src/resources/themes/corevance: .gitkeep
Only in corevance/corevance-investor/src/test/java: .gitkeep
Only in corevance/corevance-investor/src/test/resources: .gitkeep
Only in corevance/corevance-loan/src/test/java: .gitkeep
Only in corevance/corevance-loan/src/test/resources: .gitkeep
Only in corevance: .git
Only in corevance: .github
Only in corevance: .gitignore
Only in apache-corevance-src-1.15.0/integration-tests/src: integrationTest
Only in apache-corevance-src-1.15.0: LICENSE
Only in corevance: LICENSE_RELEASE
Only in corevance: LICENSE_SOURCE
Only in apache-corevance-src-1.15.0: NOTICE
Only in corevance: NOTICE_RELEASE
Only in corevance: NOTICE_SOURCE
Only in apache-corevance-src-1.15.0: .rat-excludes
Only in apache-corevance-src-1.15.0: test-results
Only in corevance: .theia
----

Make sure the code compiles and tests pass on the uncompressed source. You should at the very least do exactly what you will ask the community to do in <<Build from source>>.

Ideally you'd build code and docs and run every possible test and check, but https://github.com/apache/corevance/actions[running everything has complex dependencies, caches, and takes many hours]. It is rarely done in practice offline / local / on developer machines. But please, go ahead and run the test and doc tasks, and more! Grab a cup of coffee and run everything you can. See the various builds in `.github/workflows/` and try the same things on your own. We should all hammer on a release candidate as much as we can to see if it breaks and fix it if so. All that of course improves our final release.

NOTE: We don't release any artifacts to Apache's Maven repository.

== Gradle Task

.Command
[source,bash]
----
./gradlew corevanceReleaseStep6
----

CAUTION: This task doesn't work. Build release artifacts manually as indicated above.
